stages:
  - deploy

# Common deploy job template
.deploy_job_template: &deploy_job_definition
  image:
    name: ${NODE}
    entrypoint: ['']
  tags:
    - shared-tests
  allow_failure: true

.deploy_script_template: &deploy_script_definition
  script:
    # Prepare web-root
    - rm -rf /data
    - mkdir -p /data/lib

    # Build SDK
    - npm ci
    - npm run dist
    - mv ./dist/* /data/lib/

    # Build Docs (VuePress)
    - cd "${CI_PROJECT_DIR}/docs"
    - npm ci
    - npm run build
    - mv ./src/.vuepress/dist/* /data

    - rm -rf "${CI_PROJECT_DIR}"

    - chown -R nginx:nginx /data
    - echo 'server { listen 80 default_server; root /data; index index.html index.htm; try_files $uri $uri/ /index.html =404; }' > /etc/nginx/conf.d/default.conf
    - |
      echo "Docs: https://${PROXY_build_DOMAIN}"
      echo "JS SDK:"
      echo "  - https://${PROXY_build_DOMAIN}/lib/livetag.js"
      echo "  - https://${PROXY_build_DOMAIN}/lib/livetag.esm.js"
    - nginx

deploy:dev:
  stage: deploy
  when: manual
  <<: *deploy_job_definition
  variables:
    PROXY_build_HTTPS: '443:80'
    PROXY_build_HTTP: '80:80'
    PROXY_build_DOMAIN: dev-${MAIN_DOMAIN}
  environment:
    name: dev
    url: https://${PROXY_build_DOMAIN}
  cache:
    key: dev-modules
    paths:
      - node_modules/
  <<: *deploy_script_definition

deploy:test:
  stage: deploy
  when: manual
  <<: *deploy_job_definition
  variables:
    PROXY_build_HTTPS: '443:80'
    PROXY_build_HTTP: '80:80'
    PROXY_build_DOMAIN: test-${MAIN_DOMAIN}
  environment:
    name: test
    url: https://${PROXY_build_DOMAIN}
  cache:
    key: test-modules
    paths:
      - node_modules/
  <<: *deploy_script_definition

deploy:live:
  stage: deploy
  when: manual
  <<: *deploy_job_definition
  variables:
    PROXY_build_HTTPS: '443:80'
    PROXY_build_HTTP: '80:80'
    PROXY_build_DOMAIN: live-${MAIN_DOMAIN}
  environment:
    name: live
    url: https://${PROXY_build_DOMAIN}
  cache:
    key: live-modules
    paths:
      - node_modules/
  only:
    - master
    - develop
    - tags
  <<: *deploy_script_definition
